{
 "title": "Tasks App Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "p50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(my_http_response_time_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http requests per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(my_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In flight http requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 22 },
   "targets": [
    { "expr": "my_http_requests_in_flight", "legendFormat": "__auto" }
   ]
  }
 ]
}