{
 "title": "Tasks Canary Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "p50 Canary Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(canary_duration_bucket[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Canary successes per second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 13 },
   "targets": [
    { "expr": "rate(canary_success[1m])" }
   ]
  },
  {
   "title": "Canary failures per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 26 },
   "targets": [
    { "expr": "rate(canary_failure[1m])" }
   ]
  }
 ]
}