apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasks
  namespace: tasks
  annotations:
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    # Enable client certificate authentication
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "tasks/ca-cert"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
spec:
  tls:
  - hosts:
    - tasks.{{ .Values.envName }}.leetcyber.com
    secretName: tasks-external-cert
  ingressClassName: external-nginx
  rules:
  - host: tasks.{{ .Values.envName }}.leetcyber.com
    http:
      paths:
      - backend:
          service:
            name: tasks
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}

