apiVersion: v1
kind: Service
metadata:
  name: tasks
  namespace: tasks
  labels:
    name: tasks
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: tasks
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-canary
  namespace: tasks
  labels:
    name: tasks-canary
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: tasks-canary


