apiVersion: v1
kind: Service
metadata:
  name: tasks
  namespace: tasks
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: wave3-app-tasks-dev
    app.kubernetes.io/name: wave3-app-tasks


