apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tasks
  namespace: tasks
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: 9000
  namespaceSelector:
    matchNames:
    - tasks
  selector:
    matchLabels:
      name: tasks
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tasks-canary
  namespace: tasks
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: 9000
  namespaceSelector:
    matchNames:
    - tasks
  selector:
    matchLabels:
      name: tasks-canary

