ingress-nginx:
  controller:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - external-ingress-nginx
            topologyKey: kubernetes.io/hostname
    metrics:
      enabled: true
      serviceMonitor:
        additionalLabels:
          release: prometheus-stack
        enabled: true
    ingressClassResource:
      name: external-nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/external-ingress-nginx"

