ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: ""
    replicaCount: 2
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - internal-ingress-nginx
            topologyKey: kubernetes.io/hostname
    metrics:
      enabled: true
      serviceMonitor:
        additionalLabels:
          release: prometheus-stack
        enabled: true
    ingressClassResource:
      name: internal-nginx
      enabled: true
      default: true
      controllerValue: "k8s.io/internal-ingress-nginx"