version: '3.9'

# stop default dns with 'sudo systemctl stop systemd-resolved'
# start the networking containers with 'docker-compose up [-d]' in this directory

services:
# for bash cli, use 'docker exec -it my-dnsmasq-container sh'
  dnsmasq:
    restart: always
    build:
      context: .
      dockerfile: dnsmasq.Dockerfile
    image: my-dnsmasq-image
    container_name: my-dnsmasq-container
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
    network_mode: "host"
    volumes:
      - /etc/hosts:/etc/hosts:ro
  # for frr cli, use 'docker exec -it my-frr-container vtysh'
  frr:
    restart: always
    build:
      context: .
      dockerfile: frr.Dockerfile
    image: my-frr-image
    container_name: my-frr-container
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE