ingress-nginx:
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        additionalLabels:
          release: prometheus-stack
        enabled: true
    ingressClassResource:
      name: internal-nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/internal-ingress-nginx"
