apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: internal-nginx
  rules:
  - host: argocd.{{ .Values.envName }}.leetcyber.com
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 443
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  tls:
  - hosts:
    - longhorn.{{ .Values.envName }}.leetcyber.com
    secretName: longhorn-internal-cert
  ingressClassName: internal-nginx
  rules:
  - host: longhorn.{{ .Values.envName }}.leetcyber.com
    http:
      paths:
      - backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  tls:
  - hosts:
    - keycloak.{{ .Values.envName }}.leetcyber.com
    secretName: keycloak-internal-cert
  ingressClassName: internal-nginx
  rules:
  - host: keycloak.{{ .Values.envName }}.leetcyber.com
    http:
      paths:
      - backend:
          service:
            name: keycloak
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: minio
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  tls:
  - hosts:
    - minio.{{ .Values.envName }}.leetcyber.com
    secretName: minio-internal-cert
  ingressClassName: internal-nginx
  rules:
  - host: minio.{{ .Values.envName }}.leetcyber.com
    http:
      paths:
      - backend:
          service:
            name: minio
            port:
              number: 9000
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: prometheus-stack
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  tls:
  - hosts:
    - prometheus.{{ .Values.envName }}.leetcyber.com
    secretName: prometheus-internal-cert
  ingressClassName: internal-nginx
  rules:
  - host: prometheus.{{ .Values.envName }}.leetcyber.com
    http:
      paths:
      - backend:
          service:
            name: prometheus-stack-kube-prom-prometheus
            port:
              number: 9090
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: prometheus-stack
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  tls:
  - hosts:
    - grafana.{{ .Values.envName }}.leetcyber.com
    secretName: grafana-internal-cert
  ingressClassName: internal-nginx
  rules:
  - host: grafana.{{ .Values.envName }}.leetcyber.com
    http:
      paths:
      - backend:
          service:
            name: prometheus-stack-grafana
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}

