apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-secret
  namespace: my-keycloak-operator
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    clientId: client-secret
    secret: client-secret
    clientAuthenticatorType: client-secret
    directAccessGrantsEnabled: true
    fullScopeAllowed: true
    publicClient: true
    redirectUris:
      - "*"
    baseUrl: "/"
    rootUrl: "http://oauth.dev.leetcyber.com"
    standardFlowEnabled: true
    defaultClientScopes:
      - "email"
      - "proflie"
