apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-ingress-metrics
  namespace: external-ingress-nginx
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - external-ingress-nginx
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-ingress-nginx
