minio:
  global:
    storageClass: longhorn
  metrics:
    serviceMonitor:
      enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/minio/v2/metrics/cluster"
    prometheus.io/port: "9000"
