prometheus-postgres-exporter:
  serviceMonitor:
    enabled: true
  config:
    datasource:
      host: tasks-postgres-repl.tasks.svc
      user: owner
      passwordSecret:
        name: owner.tasks-postgres.credentials.postgresql.acid.zalan.do
        key: password
      database: app
